Resources:
   MyStageEc2Intance:
     Type: AWS::EC2::Instance
     Properties:
        ImageId: ami-0d542ef84ec55d71c
        InstanceType: "t2.micro"
        KeyName: "DevKey"
        SecurityGroups:
          - default   