Parameters:
  MyDevKeyName:
    Description: Please enter the KeyName 
    Type: AWS::EC2::KeyPair::KeyName
  EnvirnomentName:
    Description: Select the enviroment type
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - Prod
Mappings:
  EnvirnomentInstanceType:
    Dev:
      Instancetype: t2.nano
    Test:  
      Instancetype: t2.micro
    Prod:  
      Instancetype: t2.small  
Conditions:
  EIPforProdCondition: !Equals [!Ref EnvirnomentName, Prod]      
  CreateDevSecurityGroup: !Equals [!Ref EnvirnomentName, Dev]
  CreateProdSecurityGroup: !Not [{Condition: CreateDevSecurityGroup}]
  AWSCreateKeyName: !And [ !Or [!Equals [!Ref 'AWS::Region',us-east-2], !Equals [ !Ref 'AWS::Region',us-west-2]], !Equals [!Ref EnvirnomentName, Dev]]
Metadata:
  AWS::Cloudformation::Interface:
    ParameterGroups:
      - Label:
          default: "Please Select the EC2 Confriguation"
        Parameters:
          - InstanceType
          - KeyName
          - AvaiabilityZone
      - Label:
          default: "Envirnoment Confirguation"
        Parameters: 
          - EnvirnomentName      
    ParameterLabels:
      EnvirnomentName:
        default:  "Which Envirnoment are planning to create the instance"
      KeyName:
        default: "Once you have selected the Keyname "   
Resources:
  DevInstance:
    Description : EC2 instance Resource
    Type : AWS::EC2::Instance    
    Properties:
      ImageId: ami-0d542ef84ec55d71c
      InstanceType: !FindInMap
        - EnvirnomentInstanceType
        - !Ref EnvirnomentName 
        - Instancetype
      KeyName: !If [AWSCreateKeyName,DevKey,production]
      SecurityGroups: 
        - !ImportValue DevSecurityGroupExportConfig
      AvailabilityZone: !ImportValue outputCondition-Avaiblityzone 
  ProdEIPInstance:
    Type: AWS::EC2::EIP
    Condition: EIPforProdCondition
    Properties:
      InstanceId: !Ref DevInstance
    

