Resources: 
  StageEc2Instance:
    Type: AWS::EC2::Instance 
    Properties:
      ImageId: ami-0d542ef84ec55d71c
      InstanceType: "t2.micro"
      KeyName: "DevKey"     
      SecurityGroups:
        - default 
        - !Ref SSHSecurityGroup
        - !Ref WindowSecurityGroup
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "EC2 Security Group"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0          
          FromPort: '80'
          ToPort: '80'
          IpProtocol: tcp
        - CidrIp : 0.0.0.0/0
          FromPort: '8080'
          ToPort: '8080'
          IpProtocol: tcp
  WindowSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Windows Security Group"
      SecurityGroupIngress:
        - CidrIp: 192.168.0.0/32          
          FromPort: '22'
          ToPort: '22'
          IpProtocol: tcp
        - CidrIp : 10.2.3.1/16
          FromPort: '8080'
          ToPort: '8080'
          IpProtocol: tcp  
  MyElasticAddress:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref StageEc2Instance
                    